# Generated by Django 2.2.5 on 2019-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20190912_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Biology'), (2, 'Chemistry'), (3, 'Physics'), (4, 'Mathematics')], null=True),
        ),
    ]
