# Generated by Django 2.2.2 on 2019-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_remove_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=1),
        ),
    ]
