# Generated by Django 2.2.2 on 2019-10-01 12:13

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to=Post.models.upload_image_path),
        ),
    ]
